spring:
  application:
    name: expenses

  datasource:
    url: jdbc:postgresql://localhost:5432/expenses_db
    username: postgres
    password: long

  jpa:
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

jwt:
  secret: G/Znwsht1C9dI57IZ0L8GLO0QZMYK7MbsE3TtyazYXU=
