spring:
  application:
    name: expenses

  datasource:
    url: jdbc:mysql://localhost:3306/expenses_db
    username: expenses
    password: Tuilasieunhan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
